# action.yml
name: "Build QIO Docker"
description: "This will rebuild the docker image if the Dockerfile has changed if not it will pull the image from the registry"
inputs:
  repository-owner:
    description: "Repository owner"
    required: true
  docker-post-build-name:
    description: "Docker post build name"
    required: true
  github-token:
    description: "Github token"
    required: true

runs:
  using: "composite"
  steps:
    - id: buildx
      uses: docker/setup-buildx-action@v2
    
    - id: registry
      shell: bash
      run: | 
        echo "${{ inputs.github-token }}" | docker login ghcr.io -u $ --password-stdin
      
    - id: build
      shell: bash
      run: |
        DOCKER_REGISTRY=ghcr.io/${{ inputs.repository-owner }}
        # Lower case everything in DOCKER_REGISTRY
        DOCKER_REGISTRY=$(echo ${DOCKER_REGISTRY} | tr '[:upper:]' '[:lower:]')
        DOCKERFILE_PATH=./Dockerfile
        IMAGE_NAME=qio_toolkit_build_environment
        SHA=$(sha256sum ${DOCKERFILE_PATH} | awk '{ print $1 }')
        TAG_NAME=${DOCKER_REGISTRY}/${IMAGE_NAME}:${SHA}
        docker pull ${TAG_NAME} && echo "Image exists in the Docker registry, no need to build." || (echo "Image doesn't exist in the Docker registry. Building now..." && docker build -t ${TAG_NAME} -f ${DOCKERFILE_PATH} . && echo "Pushing image to Docker registry..." && docker push ${TAG_NAME})
        docker tag ${TAG_NAME} ${{ inputs.docker-post-build-name }}
        