
name: QIO Documentation build

on:
  push:
    branches: 
      - main
      - feature/ci-workflow-integration
  pull_request:
    branches: 
      - main

env:
    DOCKER_BUILDKIT: 1
    DOCKER_POST_BUILD_NAME: qio_toolkit_build_environment

jobs:   
    build-documentation:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
        - uses: actions/checkout@v3

        - name: Log in to registry
          run: | 
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
            
        - name: Build the Docker image
          uses: ./.github/build_docker
          with:
            repository-owner: ${{ github.repository_owner }}
            docker-post-build-name: ${{ env.DOCKER_POST_BUILD_NAME }}
        
        - name: Build documentation
          run: |
            docker run -v $(pwd):/workdir -w /workdir ${{ env.DOCKER_POST_BUILD_NAME }} bash -c "make build-documentation"